### ISSUE TITLE
There are a couple of strange links at the top of contact pages which when clicked opens a blank page

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#13] opened 2018-01-14 16:03 UTC
In contact page, there are a few links at top which when clicked takes us to a blank page.

And, email address of "Principal Contact" and "Support contact" is missing.

**Comment by Vitaliy-1** [comment] 2018-01-14 16:07
Hmm. I don't observe such behaviour... 
http://ojsdemo.e-medjournal.com/index.php/oldGregg/about/contact

**Comment by anupent** [comment] 2018-01-14 16:12
This is from manuscript-JATS
![image](https://user-images.githubusercontent.com/15881295/34918047-73a72dc8-f975-11e7-8954-e5b902b75f04.png)

And this is from the oldGregg
![image](https://user-images.githubusercontent.com/15881295/34918060-952972bc-f975-11e7-80e4-ffb740bf8f46.png)

And this is "Journal Settings" - contacts
![image](https://user-images.githubusercontent.com/15881295/34918086-d6c76800-f975-11e7-97a0-ad409eafde42.png)

Similarly I get a blank page in "Editorial team"
![image](https://user-images.githubusercontent.com/15881295/34918097-f92ceeec-f975-11e7-9d7d-5b499728f48f.png)

**Comment by Vitaliy-1** [comment] 2018-01-14 16:17
@anupent 
Hmm, this is very strange. You can compare `contact` page with the default by yourself:
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/pages/contact.tpl
https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/contact.tpl

And editorial team page:
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/pages/editorialTeam.tpl
https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/editorialTeam.tpl

You can try also rewrite them with default pages and compare the result.

**Comment by anupent** [comment] 2018-01-14 16:19
My editorial team title in masthead is not translated. Can it be a cause?
![image](https://user-images.githubusercontent.com/15881295/34918185-c73a1904-f976-11e7-8e3d-5e56f8ec1db7.png)

I will check as you above advice.

**Comment by Vitaliy-1** [comment] 2018-01-14 16:21
Nope. 
Can you inspect those pages with Chrome or FireFox tools?  Did you see, for example, this element on contact page: https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/pages/contact.tpl#L18

**Comment by Vitaliy-1** [comment] 2018-01-14 16:24
As for Editorial Page, I can reproduce the problem. it's quite bizarre. Will look more closely.

**Comment by anupent** [comment] 2018-01-14 16:30
I found the problem with contacts. 
There was some strange links at the top of contact page and i made a css rule to display:none. This rule affected the email fields also. 
I deleted that css rule and email is visible.
But, what is this links at the top of contacts that takes me to a blank page?
![image](https://user-images.githubusercontent.com/15881295/34918285-627c7a28-f978-11e7-9d51-52709f812e8d.png)

**Comment by Vitaliy-1** [comment] 2018-01-14 16:32
Can you test that link with the default theme?

**Comment by anupent** [comment] 2018-01-14 16:35
I get a blank page for that link with the manuscript-JATS too.

**Comment by anupent** [comment] 2018-01-14 16:46
Similar links in the announcement page too.
![image](https://user-images.githubusercontent.com/15881295/34918454-b3d105cc-f97a-11e7-98cd-126b0603d37d.png)

**Comment by Vitaliy-1** [comment] 2018-01-14 16:58
Can you try to press the contact link with this fix applied?

**Comment by Vitaliy-1** [comment] 2018-01-14 17:00
I haven't changed announcement page in any way :(

**Comment by anupent** [comment] 2018-01-14 17:07
bravo! fixed.
When logged in, there is that link which takes us to the contact settings.
When not logged in, that link does not appear.

**Comment by Vitaliy-1** [comment] 2018-01-14 17:07
I have tested the link to edit announcements and it's working as expected. 
Also, the link in oldGregg and default theme are exactly the same:
http://domain.com/index.php/psp/management/settings/website#announcements
and
http://domain.com/index.php/psp/management/settings/website#announcements

Can you check if you have the same link under `edit` on the announcement page?

**Comment by anupent** [comment] 2018-01-14 17:11
The link in the announcement page takes us to appearance under website settings. 
We can live with this.
However, in case of links in contact page, it takes us to the proper tab "contact".

**Comment by Vitaliy-1** [comment] 2018-01-14 17:18
I think you have discovered a bug in OJS

**Comment by Vitaliy-1** [comment] 2018-01-14 17:28
Ok. I have copied original OJS page and have changed it a bit. The link should work properly.

**Comment by Vitaliy-1** [comment] 2018-01-14 17:34
@anupent 
You can close the issue, if it works

**Comment by anupent** [comment] 2018-01-14 17:38
Even with the fix, it still takes me to "appearance" tab of "website settings".

**Comment by Vitaliy-1** [comment] 2018-01-14 17:40
Hmm, It can be needed to clear the template cache (because of new template file).
Also, the link should look like this:
http://emedjournal.com/index.php/psp/management/settings/website#ui-id-11

Is it the same in your case?

**Comment by Vitaliy-1** [comment] 2018-01-14 17:42
`#ui-id-11` is the id of the announcement tab.

**Comment by anupent** [comment] 2018-01-14 17:43
It still takes me to the "appearance" tab, even with the #ui-id-11 in the link.
![image](https://user-images.githubusercontent.com/15881295/34918885-a99f3e9a-f982-11e7-8e88-99dba17721b6.png)

**Comment by Vitaliy-1** [comment] 2018-01-14 17:47
![id](https://user-images.githubusercontent.com/20665587/34918911-c9217cc0-f963-11e7-97b6-866df111cd74.jpg)

**Comment by anupent** [comment] 2018-01-14 17:50
It is exactly the same like yours.
![image](https://user-images.githubusercontent.com/15881295/34918932-98f35530-f983-11e7-9e5c-742329a21e9e.png)

**Comment by anupent** [comment] 2018-01-14 17:52
I think i need to retire today. I have a surgery tomorrow. Good night.

**Comment by Vitaliy-1** [comment] 2018-01-14 17:54
Bye. Thanks. I have also opened the issue on OJS page about this problem: https://github.com/pkp/pkp-lib/issues/3273

**Closed** 2018-01-15 02:49 UTC

**Comment by Vitaliy-1** [comment] 2018-01-17 20:37
@anupent 
PKP team has provided a different fix for the problem with announcement link. We need to keep this in mind and correct the code on the next OJS release.
